# Generated by Django 3.1.6 on 2021-04-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remotefollowers',
            options={'verbose_name': 'Remote Follower', 'verbose_name_plural': 'Remote Followers'},
        ),
        migrations.AlterModelOptions(
            name='remotefriends',
            options={'verbose_name': 'Remote Friend', 'verbose_name_plural': 'Remote Friends'},
        ),
        migrations.RemoveField(
            model_name='remotefriends',
            name='remote_friends',
        ),
        migrations.AddField(
            model_name='remotefriends',
            name='remote_friend',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddConstraint(
            model_name='remotefriends',
            constraint=models.UniqueConstraint(fields=('local_author', 'remote_friend'), name='remote_friends'),
        ),
    ]
