# Generated by Django 3.1.6 on 2021-04-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_json',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='foreignserver',
            name='host_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='objectlike',
            name='author_json',
            field=models.TextField(default=''),
        ),
    ]
