# Generated by Django 3.1.6 on 2021-03-04 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0002_auto_20210304_0409'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikedPosts',
            new_name='LikedPost',
        ),
    ]
