# Generated by Django 3.1.6 on 2021-04-12 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0002_auto_20210411_2237'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RemoteFollow',
        ),
    ]
