# Generated by Django 3.1.6 on 2021-03-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0002_auto_20210303_2019'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='followers',
            constraint=models.UniqueConstraint(fields=('author', 'follower'), name='unique_follow'),
        ),
    ]
