# Generated by Django 3.1.6 on 2021-03-28 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0002_auto_20210324_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followers',
            options={'verbose_name': 'Followers', 'verbose_name_plural': 'Followers'},
        ),
    ]
