# Generated by Django 3.1.6 on 2021-04-16 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0002_auto_20210416_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotefriends',
            name='local_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
