# Generated by Django 3.1.6 on 2021-03-28 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0003_auto_20210327_2238'),
        ('SocialApp', '0003_auto_20210327_2002'),
    ]

    operations = [
    ]
