# Generated by Django 3.1.6 on 2021-04-16 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0003_auto_20210416_1451'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RemoteFriends',
        ),
    ]
