# Generated by Django 3.1.6 on 2021-03-16 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0003_auto_20210304_0417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text_content',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_content',
        ),
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.CharField(default='socialdistributionproject.herokuapp.com', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='likedpost',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='SocialApp.post'),
        ),
    ]
