# Generated by Django 3.1.6 on 2021-04-12 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0003_delete_remotefollow'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_author_to', models.CharField(editable=False, max_length=200)),
                ('local_author_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_following', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='remotefollow',
            constraint=models.UniqueConstraint(fields=('local_author_from', 'remote_author_to'), name='remote_follow'),
        ),
    ]
