# Generated by Django 3.1.6 on 2021-04-17 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0004_auto_20210412_0246'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteFollowers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_author_from', models.CharField(editable=False, max_length=200)),
                ('local_author_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Remote Follower',
                'verbose_name_plural': 'Remote Followers',
            },
        ),
        migrations.AddConstraint(
            model_name='remotefollowers',
            constraint=models.UniqueConstraint(fields=('remote_author_from', 'local_author_to'), name='remote_followers'),
        ),
    ]
