# Generated by Django 3.1.6 on 2021-03-06 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0002_auto_20210305_2156'),
        ('SocialApp', '0004_auto_20210306_1435'),
    ]

    operations = [
    ]
