# Generated by Django 3.1.6 on 2021-03-05 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0004_auto_20210304_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='to_author', to='SocialApp.author'),
        ),
        migrations.AlterField(
            model_name='followers',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_author', to='SocialApp.author'),
        ),
    ]
