# Generated by Django 3.1.6 on 2021-03-09 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0005_merge_20210306_1442'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inbox',
        ),
    ]
