# Generated by Django 3.1.6 on 2021-04-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0005_likedcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('authors_url', models.CharField(blank=True, max_length=200)),
                ('authors_json_key', models.CharField(blank=True, max_length=25)),
                ('posts_url', models.CharField(blank=True, max_length=200)),
                ('posts_json_key', models.CharField(blank=True, max_length=25)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=25)),
            ],
            options={
                'verbose_name': 'Foreign Server',
                'verbose_name_plural': 'Foreign Servers',
            },
        ),
    ]
