# Generated by Django 3.1.6 on 2021-04-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0006_foreignserver'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_url', models.CharField(max_length=200)),
                ('object_url', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Liked Object',
                'verbose_name_plural': 'Liked Objects',
            },
        ),
        migrations.RemoveField(
            model_name='likedpost',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='likedpost',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='post',
            name='source',
        ),
        migrations.AddField(
            model_name='comment',
            name='author_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.CharField(default='localhost:8000', editable=False, max_length=100),
        ),
        migrations.DeleteModel(
            name='LikedComment',
        ),
        migrations.DeleteModel(
            name='LikedPost',
        ),
        migrations.AddConstraint(
            model_name='objectlike',
            constraint=models.UniqueConstraint(fields=('author_url', 'object_url'), name='unique_like'),
        ),
    ]
