# Generated by Django 3.1.6 on 2021-04-11 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0006_foreignserver'),
        ('SocialApp', '0005_auto_20210401_1355'),
    ]

    operations = [
    ]
