# Generated by Django 3.1.6 on 2021-04-10 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0006_foreignserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxitem',
            name='json_str',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='link',
            field=models.TextField(default=''),
        ),
    ]
