# Generated by Django 3.1.6 on 2021-03-22 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0004_auto_20210315_1840'),
        ('SocialApp', '0006_delete_inbox'),
    ]

    operations = [
    ]
