# Generated by Django 3.1.6 on 2021-04-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0007_merge_20210411_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotefollow',
            name='remote_author_to',
            field=models.CharField(editable=False, max_length=200),
        ),
    ]
