# Generated by Django 3.1.6 on 2021-04-11 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0007_auto_20210411_1155'),
        ('SocialApp', '0007_auto_20210410_1748'),
    ]

    operations = [
    ]
