# This is a basic workflow to help you get started with Actions

name: SocialAppCI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8] #3.6,3.7

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      #Set up Backend (Django)
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies for Backend 
        run: |
          python -m pip install --upgrade pip
          pip install -r ./github_requirements.txt
      - name: DB Migrations
        run: python3 ./mysite/manage.py migrate
    
      #Run Backend Tests
      - name: Run Django tests 
        run: python3 ./mysite/manage.py test SocialApp #run all files in SocialApp app that start with "test"
